name: Build and Publish Docker Image 1

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.TOKEN_FOR_PACKAGES }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 \
          --push \
          -t ghcr.io/${{ github.repository }}/my-python-app:latest .

    - name: Logout from GitHub Container Registry
      run: docker logout ghcr.io
